apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0          # Zero-downtime rolling updates
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: tejasops/flask-api:latest   # Replace with your Docker Hub image
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: APP_ENV
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu:    "100m"
            limits:
              memory: "128Mi"
              cpu:    "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
