apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  type: NodePort             # External access for testing
  ports:
    - protocol: TCP
      port: 80              # Service port
      targetPort: 5000      # Container port
